In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set_theme(style="whitegrid")
import matplotlib

In [2]:
acc_count_attractor_BL = np.array([[0.92, 0.86, 0.88, 0.89, 0.89, 0.9], [0.85, 0.75, 0.79, 0.81, 0.8, 0.83], [0.91, 0.74, 0.78, 0.79, 0.82, 0.82], \
                       [0.91, 0.77, 0.82, 0.8, 0.84, 0.83], \
                       [0.92, 0.8, 0.84, 0.87, 0.85, 0.87],\
                        [0.84, 0.69, 0.69, 0.69, 0.69, 0.69]]).T
acc_count_attractor_BB = np.array([[0.90, 0.84, 0.86, 0.87, 0.87, 0.88], [0.85, 0.76, 0.79, 0.81, 0.8, 0.82], [0.85, 0.77, 0.79, 0.81, 0.81, 0.83], \
                       [0.91, 0.82, 0.86, 0.86, 0.87, 0.87], \
                       [0.92, 0.79, 0.83, 0.86, 0.85, 0.87],\
                        [0.82, 0.62, 0.69, 0.62, 0.62, 0.67]]).T

acc_count_attractor_RB = np.array([[0.92, 0.85, 0.87, 0.89, 0.88, 0.9], [0.86, 0.78, 0.79, 0.83, 0.8, 0.84], [0.8, 0.79, 0.78, 0.78, 0.78, 0.78], \
                       [0.91, 0.84, 0.87, 0.88, 0.87, 0.88], \
                       [0.94, 0.81, 0.86, 0.88, 0.87, 0.89],\
                        [0.69, 0.52, 0.56, 0.53, 0.58, 0.53]]).T

acc_count_attractor_GS = np.array([[0.79, 0.77, 0.77, 0.77, 0.77, 0.77], [0.79, 0.7, 0.74, 0.75, 0.76, 0.78], [0.89, 0.77, 0.79, 0.8, 0.79, 0.83], \
                       [0.89, 0.81, 0.83, 0.85, 0.84, 0.86], \
                       [0.92, 0.81, 0.82, 0.86, 0.83, 0.84],\
                        [0.78, 0.61, 0.57, 0.55, 0.59, 0.6]]).T

acc_count_attractor_RL = np.array([[0.94, 0.86, 0.88, 0.9, 0.9, 0.92], [0.88, 0.72, 0.78, 0.84, 0.81, 0.86], [0.92, 0.72, 0.72, 0.74, 0.72, 0.73], \
                       [0.89, 0.81, 0.83, 0.85, 0.84, 0.86], \
                       [0.96, 0.81, 0.84, 0.88, 0.86, 0.9],\
                        [0.83, 0.52, 0.57, 0.51, 0.52, 0.57]]).T

acc_count_attractor_GM = np.array([[0.79, 0.77, 0.77, 0.77, 0.77, 0.77], [0.79, 0.7, 0.74, 0.75, 0.76, 0.78], [0.89, 0.77, 0.79, 0.8, 0.79, 0.83], \
                       [0.89, 0.81, 0.83, 0.85, 0.84, 0.86], \
                       [0.92, 0.81, 0.82, 0.86, 0.83, 0.84],\
                        [0.78, 0.61, 0.57, 0.55, 0.59, 0.6]]).T

In [3]:
df_BL = pd.DataFrame(acc_count_attractor_BL, columns=['MNLI', 'MRPC', 'PAWS', 'QQP', 'SST-2', 'CoLA']).iloc[:2, :]
df_BB = pd.DataFrame(acc_count_attractor_BB, columns=['MNLI', 'MRPC', 'PAWS', 'QQP', 'SST-2', 'CoLA']).iloc[:2, :]
df_RB = pd.DataFrame(acc_count_attractor_RB, columns=['MNLI', 'MRPC', 'PAWS', 'QQP', 'SST-2', 'CoLA']).iloc[:2, :]
df_GS = pd.DataFrame(acc_count_attractor_GS, columns=['MNLI', 'MRPC', 'PAWS', 'QQP', 'SST-2', 'CoLA']).iloc[:2, :]
df_RL = pd.DataFrame(acc_count_attractor_RL, columns=['MNLI', 'MRPC', 'PAWS', 'QQP', 'SST-2', 'CoLA']).iloc[:2, :]
df_GM = pd.DataFrame(acc_count_attractor_GM, columns=['MNLI', 'MRPC', 'PAWS', 'QQP', 'SST-2', 'CoLA']).iloc[:2, :]

In [110]:
dataset = [df_BB, df_BL, df_RB, df_RL, df_GS, df_GM]
models = ['$Bert^{B}$', '$Bert^{L}$', '$Roberta^{B}$', '$Roberta^{L}$', '$GPT2^{S}$', '$GPT2^{M}$']
res = []
for idx, df in enumerate(dataset):
    df['Model'] = models[idx]
    df['Ordering'] = ''
    df.at[0, 'Ordering'] = 'Original'
    df.at[1, 'Ordering'] = 'Full Shuffle'
    res.append(df)
rdf = pd.concat(res, axis=0)
rdf

   MNLI  MRPC  PAWS   QQP  SST-2  CoLA          Model      Ordering
0  0.90  0.85  0.85  0.91   0.92  0.82     $Bert^{B}$      Original
1  0.84  0.76  0.77  0.82   0.79  0.62     $Bert^{B}$  Full Shuffle
0  0.92  0.85  0.91  0.91   0.92  0.84     $Bert^{L}$      Original
1  0.86  0.75  0.74  0.77   0.80  0.69     $Bert^{L}$  Full Shuffle
0  0.92  0.86  0.80  0.91   0.94  0.69  $Roberta^{B}$      Original
1  0.85  0.78  0.79  0.84   0.81  0.52  $Roberta^{B}$  Full Shuffle
0  0.94  0.88  0.92  0.89   0.96  0.83  $Roberta^{L}$      Original
1  0.86  0.72  0.72  0.81   0.81  0.52  $Roberta^{L}$  Full Shuffle
0  0.79  0.79  0.89  0.89   0.92  0.78     $GPT2^{S}$      Original
1  0.77  0.70  0.77  0.81   0.81  0.61     $GPT2^{S}$  Full Shuffle
0  0.79  0.79  0.89  0.89   0.92  0.78     $GPT2^{M}$      Original
1  0.77  0.70  0.77  0.81   0.81  0.61     $GPT2^{M}$  Full Shuffle

In [ ]:
fig, ax = plt.subplots(2, 3, figsize=(20, 8))
plt.subplots_adjust(top = 1.0, bottom=0.01, hspace=1.0, wspace=0.33)
# plt.tight_layout()
r, c = 0, 0
for ds in rdf.columns.difference(['Model', 'Ordering']):
    if c == 3:
        r = 1
        c = 0
    sns.set(font_scale = 2.0)
    g = sns.barplot(data=rdf[[ds, 'Model', 'Ordering']], x = 'Model', y = ds, hue='Ordering', ax=ax[r][c])
    ax[r][c].tick_params(axis='x', rotation=45)
    if r == 0 and c == 0:
        handles, labels = ax[r][c].get_legend_handles_labels()
        fig.legend(handles, labels, loc='lower center', bbox_to_anchor=[0.5, 1.05], ncol=2)
    ax[r][c].legend([],[], frameon=False)
    ax[r][c].set_ylabel('Accuracy', fontsize=28)
    ax[r][c].set_xlabel('')
    ax[r][c].set_ylim([0, 1])
    ax[r][c].set_title(ds)
    c += 1

fig.savefig('barplot.png',dpi=300, bbox_inches = "tight")